### ISSUE TITLE
Error: fetch failed with status code 502

### ISSUE THREAD

**Issue by willalston** [sindresorhus/clone-regexp#1]
Getting bad gateway on the path - http://registry.npmjs.org/clone-regexp/-/clone-regexp-1.0.0.tgz. Any chance this will be restored soon? By the way... stops the YEOMAN install because of dependency!!

**Comment by sindresorhus** [comment]
That's a problem with your connection. Use https://github.com/npm/npm/issues for npm related issues.

**Comment by willalston** [comment]
Didn't think it was because 10+ ppl had the issue in a corporate environment and it was the only package not installing. Either way, it's back online as of around 11:30a (EST). I appreciate the reply. Have a great day and we appreciate your work.
